name:           TestSimple
version:        0.2.1

ghc-options: -Wall
description: 
    version 0.2.1 - to test my lualatex call
dependencies:
  - base  
  - uniform-error
  - uniform-strings
  - uniform-fileio
  - process

library:
  source-dirs: .

executables:
  foo:
    main: MyMain.hs
    source-dirs: src
    dependencies: 
      - TestSimple
      # - base  
      # - uniform-error
      # - uniform-strings
      # - uniform-fileio
      # - process
tests:
  test1:
    main: Testing.hs
    source-dirs: tests
    dependencies: 
      - TestSimple
      - HTF
      # - base  
      # - uniform-error
      # - uniform-strings
      # - uniform-fileio
      # - process

