flags: {}
extra-package-dbs: []
packages:
- '.'
 

extra-deps: 
- ../uniform/uniform-strings
- ../uniform/uniform-algebras
- ../uniform/uniform-convenience
- ../uniform/uniform-cmdLineArgs
- ../uniform/uniform-fileio
# - ../uniform/uniform-ftp
- ../uniform/uniform-time
- ../uniform/uniform-error
- ../uniform/uniform-json
- ../uniform/uniform-pandoc

- test-invariant-0.4.5.0


resolver: lts-16.0
